import Link from "next/link";

const principles = [["1", "Show who you are", "Build a profile that captures your work, interests, and the connection you want."], ["2", "Discover with intention", "Explore people and local businesses with thoughtful controls and clear context."], ["3", "Connect safely", "Mutual matches unlock conversations; reporting and blocking are always close at hand."]];
const ads = ["Independent design studio", "Weekend language salon", "Wellness practice"];

export default function Home() {
  return <><section className="overflow-hidden bg-[#172033] py-16 text-white md:py-24"><div className="shell grid items-center gap-12 md:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow text-[#aebeff]">Professional dating · local discovery</p><h1 className="mt-4 max-w-2xl text-5xl font-black leading-[1.02] tracking-tight md:text-7xl">Make room for the right connection.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Linkwell brings professional ambition, shared interests, and local discovery together—without sacrificing privacy or safety.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="button bg-[#f3b36e] text-[#172033]">Create your profile</Link><Link href="/advertisements" className="button border border-slate-500 text-white">Explore local ads</Link></div><p className="mt-5 text-sm text-slate-400">For adults 18+ · Profiles are never indexed by search engines.</p></div><div className="relative mx-auto w-full max-w-sm rounded-3xl border border-slate-600 bg-gradient-to-br from-[#3157d5] to-[#17347e] p-6 shadow-2xl"><p className="text-sm font-bold text-[#dce4ff]">Designed for depth</p><p className="mt-12 text-3xl font-bold leading-tight">“My work is a part of me, but it is not all of me.”</p><div className="mt-12 flex items-center gap-3"><div className="h-12 w-12 rounded-full bg-[#f3b36e]"/><div><p className="font-bold">Avery, 31</p><p className="text-sm text-[#dce4ff]">Urban designer · Casablanca</p></div></div></div></div></section>
  <section className="shell py-20"><p className="eyebrow">How Linkwell works</p><h2 className="mt-3 max-w-xl text-4xl font-black tracking-tight">A better starting point for real-world connection.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{principles.map(([number,title,copy]) => <article key={number} className="card p-6"><span className="text-sm font-black text-[#3157d5]">0{number}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></section>
  <section className="bg-[#e7edff] py-20"><div className="shell grid gap-10 md:grid-cols-2"><div><p className="eyebrow">Dating, thoughtfully</p><h2 className="mt-3 text-4xl font-black tracking-tight">Your career and your character can both belong in the picture.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Use interests, goals, and professional context to find compatible people. You choose what is visible and who can reach you.</p><Link href="/dating" className="button button-primary mt-7">Explore dating</Link></div><div className="card p-7"><p className="font-bold">Built-in boundaries</p><ul className="mt-5 grid gap-4 text-slate-700"><li>✓ Mutual matching before direct messages</li><li>✓ Granular profile and location visibility</li><li>✓ Server-enforced blocks and reports</li><li>✓ Human moderation for safety concerns</li></ul></div></div></section>
  <section className="shell py-20"><p className="eyebrow">Local discovery</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><h2 className="text-4xl font-black tracking-tight">Find work worth talking about.</h2><Link href="/advertisements" className="font-bold text-[#3157d5]">Browse all advertisements →</Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{ads.map((name, i) => <article key={name} className="card overflow-hidden"><div className={`h-40 ${["bg-[#d8e1ff]","bg-[#fae4c8]","bg-[#d4eee5]"][i]}`}/><div className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Featured locally</p><h3 className="mt-2 text-xl font-bold">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">A considered listing from the Linkwell community.</p></div></article>)}</div></section>
  <section className="shell mb-4"><div className="rounded-3xl bg-[#dc6f55] px-7 py-12 text-white md:px-12"><p className="eyebrow text-[#ffe0d7]">Start with intent</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-tight">A more considered kind of online connection is possible.</h2><Link href="/register" className="button mt-7 bg-white text-[#172033]">Join Linkwell</Link></div></section></>;
}
